plugin:
  tx_news:
    view:
      layoutRootPath: 'EXT:headless_news/Resources/Private/Layouts/'
      partialRootPath: 'EXT:headless_news/Resources/Private/Partials/'
      templateRootPath: 'EXT:headless_news/Resources/Private/Templates/'